/* Generated by uncomputation_demo.py --emit-js-fixture. Do not edit.
 * Reference values from the Python/PennyLane implementation, used by
 * verify_core.js to check the JavaScript simulator against it. */
var FIXTURE = {
  "n_data": 4,
  "n_steps": 5,
  "seed": 20240517,
  "basis_bits": [
    0,
    0,
    1,
    1
  ],
  "steps": [
    {
      "qubits": [
        1,
        2,
        0
      ],
      "negations": [
        false,
        true,
        false
      ],
      "theta": 4.63821019600331
    },
    {
      "qubits": [
        3,
        1,
        0
      ],
      "negations": [
        false,
        false,
        true
      ],
      "theta": 1.5512463112956068
    },
    {
      "qubits": [
        1,
        3,
        0
      ],
      "negations": [
        true,
        true,
        false
      ],
      "theta": 3.543057761826832
    },
    {
      "qubits": [
        1,
        3,
        2
      ],
      "negations": [
        true,
        true,
        false
      ],
      "theta": 3.2210109469101087
    },
    {
      "qubits": [
        1,
        2,
        3
      ],
      "negations": [
        false,
        true,
        true
      ],
      "theta": 6.107978384727148
    }
  ],
  "expected": {
    "naive_total_qubits": 14,
    "naive_ancillas": 10,
    "uncomputed_total_qubits": 6,
    "entropy_before": 1.061278124459133,
    "entropy_after": 6.406853007629834e-16,
    "purity_before": 0.5937499999999993,
    "purity_after": 0.9999999999999991,
    "fidelity_uncomputed_vs_ideal": 0.9999999999999989,
    "fidelity_naive_uniform": 0.17968749999999992,
    "trace_distance_naive_uniform": 0.8411397770990292,
    "fidelity_naive_basis": 1.0
  }
};
if (typeof module !== 'undefined' && module.exports) module.exports = FIXTURE;
